In [ ]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1, as_frame=False) #since Scikit-Learn 0.24, fetch_openml() returns a Pandas DataFrame by default so use as_frame=False.
mnist.keys()


dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [ ]:
x, y = mnist["data"], mnist["target"]

In [ ]:
import numpy as np 
y=y.astype(np.uint8)

In [ ]:
x_train, x_test, y_train, y_test = x[:55000], x[55000:], y[:55000], y[55000:]

In [ ]:
from sklearn.linear_model import SGDClassifier

In [ ]:
from sklearn.multiclass import OneVsOneClassifier
from sklearn.multiclass import OneVsRestClassifier

In [ ]:
onevsrest=OneVsRestClassifier(SGDClassifier(random_state=42))

In [ ]:
onevsrest.fit(x_train,y_train)

OneVsRestClassifier(estimator=SGDClassifier(random_state=42))

In [ ]:
some_digit=x[6]
some_digitt=x[2]
some_digittt=x[79]

onevsrest.predict([some_digit])


array([1], dtype=uint8)

In [ ]:
onevsrest.predict([some_digitt])

array([4], dtype=uint8)

In [ ]:
onevsrest.predict([some_digittt])

array([7], dtype=uint8)

In [ ]:
#no of estimators used in one vs all
len(onevsrest.estimators_)

10

In [ ]:
onevsone=OneVsOneClassifier(SGDClassifier(random_state=42))

In [ ]:
onevsone.fit(x_train,y_train)


OneVsOneClassifier(estimator=SGDClassifier(random_state=42))

In [ ]:
digit=x[5]

In [ ]:
onevsone.predict([some_digit])

array([1], dtype=uint8)

In [ ]:
onevsone.predict([some_digitt])

array([4], dtype=uint8)

In [ ]:
onevsone.predict([digit])

array([2], dtype=uint8)

In [ ]:
#no.of estimators used in one vs one 
len(onevsone.estimators_)

45

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf=RandomForestClassifier()

In [ ]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
rf.predict([some_digit])

array([1], dtype=uint8)

In [ ]:
rf.classes_

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [ ]:
rf.score(x_test,y_test)

0.9725333333333334

97% accuracy